Update trial2.yml

diff --git a/.github/workflows/trial2.yml b/.github/workflows/trial2.yml
--- a/.github/workflows/trial2.yml
+++ b/.github/workflows/trial2.yml
@@ -91,10 +91,10 @@ jobs:
           echo "::set-output name=Fail2::$fail2"
           echo "${{steps.step5.outputs.Fail2}}"
         id: step5
-        if: ${{(steps.step4.outputs.Hour < '21') && (steps.step4.outputs.Hour >= '1') && ((needs.job1.outputs.output2 =='SUCCESS') ||
-            (needs.job1.outputs.output2 =='FAILURE') || (needs.job1.outputs.output2 =='UNSTABLE')) &&
-            (steps.step5.outputs.Fail2 == 'True') }}
-      - run: echo "send mail"
+        #if: ${{(steps.step4.outputs.Hour < '21') && (steps.step4.outputs.Hour >= '1') && ((needs.job1.outputs.output2 =='SUCCESS') ||
+        #    (needs.job1.outputs.output2 =='FAILURE') || (needs.job1.outputs.output2 =='UNSTABLE')) &&
+         #   (steps.step5.outputs.Fail2 == 'True') }}
+      #- run: echo "send mail"
       
       
           
