Update trial2.yml

diff --git a/.github/workflows/trial2.yml b/.github/workflows/trial2.yml
--- a/.github/workflows/trial2.yml
+++ b/.github/workflows/trial2.yml
@@ -1,5 +1,5 @@
 
-on: pull_request
+on: push
 
 jobs:
   job1:
@@ -75,33 +75,6 @@ jobs:
           echo "${{steps.step2.outputs.formatteddate}}"
           echo "${{steps.step3.outputs.DOWN_BUS}}"
           
-      - name: get hour
-        run: |
-          $output = python .github/workflows/hour.py
-          echo "::set-output name=Hour::$output"
-        id: step4
-          
-      - name: Print op
-        run: |
-          echo "${{steps.step4.outputs.Hour}}"
-          
-      - name: it has exceeded threshold limit for msg plz take action send mail
-        run: |
-          $output = python .github/workflows/fail2.py
-          echo "::set-output name=Fail2::$output"
-        id: step5
-   
-        
-      - name: Print op
-        run: |
-          echo "${{steps.step5.outputs.Fail2}}"
-        
-      - name: mail case
-        if: ${{(steps.step4.outputs.Hour < '21') && (steps.step4.outputs.Hour >= '01') && ((needs.job1.outputs.output2 =='SUCCESS') ||
-             (needs.job1.outputs.output2 =='FAILURE') || (needs.job1.outputs.output2 =='UNSTABLE')) &&
-             (steps.step5.outputs.Fail2 == 'Match')}}
-        run: |
-          echo "send mail"
           
   email-part:
     runs-on: windows-latest
@@ -110,12 +83,49 @@ jobs:
     - name: checkout
       uses: actions/checkout@v2.4.2
       
+    - name : take file
+      run: | 
+        echo "${{needs.job1.outputs.output1}}"
+        echo "${{needs.job1.outputs.output1}}" > abc1.txt
+           
+    - name: setup Python
+      uses: actions/setup-python@v3
+        
+    - name: install dependencies
+      run : python -m pip install pytz
+      
+    - name: get hour
+      run: |
+        $output = python .github/workflows/hour.py
+        echo "::set-output name=Hour::$output"
+        id: step1
+          
+    - name: Print op
+      run: |
+        echo "${{steps.step1.outputs.Hour}}"
+          
+    - name: it has exceeded threshold limit for msg plz take action send mail
+      run: |
+        $output = python .github/workflows/fail2.py
+        echo "::set-output name=Fail2::$output"
+        id: step2
+   
+    - name: Print op
+      run: |
+        echo "${{steps.step2.outputs.Fail2}}"
+        
+    - name: mail case
+      if: ${{(steps.step1.outputs.Hour < '21') && (steps.step1.outputs.Hour >= '01') && ((needs.job1.outputs.output2 =='SUCCESS') ||
+           (needs.job1.outputs.output2 =='FAILURE') || (needs.job1.outputs.output2 =='UNSTABLE')) &&
+           (steps.step2.outputs.Fail2 == 'Match')}}
+      run: |
+        echo "send mail"
       
           
           
 
 
        
-        # && log string ==it has exceeded threshold limit for msg plz take action (check on if case)
+       
           
   
