Update trial2.yml

diff --git a/.github/workflows/trial2.yml b/.github/workflows/trial2.yml
--- a/.github/workflows/trial2.yml
+++ b/.github/workflows/trial2.yml
@@ -151,9 +151,10 @@ jobs:
         echo "send mail case3"
           
     - name: mail case4 GET MINUTE HERE
-      if: ${{(steps.step1.outputs.Hour == '07') && (steps.step2.outputs.Minute >= '50'&& steps.step2.outputs.Minute <= '59') && ((needs.job1.outputs.output2 =='SUCCESS') ||
-           (needs.job1.outputs.output2 =='FIXED') || (needs.job1.outputs.output2 =='UNSTABLE')) &&
-           (steps.step3.outputs.Fail2 == 'has exceeded threshold limit for messages. Please take action!')}}
+      if: ${{(steps.step1.outputs.Hour == '07') && ((steps.step2.outputs.Minute >= '50')&& (steps.step2.outputs.Minute <= '59'))&& ((needs.job1.outputs.output2 =='SUCCESS') ||
+           (needs.job1.outputs.output2 =='FIXED') || (needs.job1.outputs.output2 =='UNSTABLE'))}}
+           #&&
+           #(steps.step3.outputs.Fail2 == 'has exceeded threshold limit for messages. Please take action!')}}
       run: |
         echo "send mail case4"
 
